#pragma once


enum ACTION {
	BASIC_SYNTHESIS,
	BASIC_TOUCH,
	MASTERS_MEND,
	OBSERVE,
	WASTE_NOT,
	VENERATION,
	STANDARD_TOUCH,
	GREAT_STRIDES,
	INNOVATION,
	FINAL_APPRAISAL,
	WASTE_NOT_II,
	BYREGOTS_BLESSING,
	MUSCLE_MEMORY,
	CAREFUL_SYNTHESIS,
	MANIPULATION,
	PRUDENT_TOUCH,
	ADVANCED_TOUCH,
	REFLECT,
	PREPARATORY_TOUCH,
	GROUNDWORK,
	DELICATE_SYNTHESIS,
	PRUDENT_SYNTHESIS,
	TRAINED_FINESSE,
	REFINED_TOUCH,
	IMMACULATE_MEND,
	TRAINED_PERFECTION,

	ACTION_COUNT
};

inline const char* actionToString(ACTION a) {
	switch (a) {
	case BASIC_SYNTHESIS: return "BASIC_SYNTHESIS";
	case BASIC_TOUCH: return "BASIC_TOUCH";
	case MASTERS_MEND: return "MASTERS_MEND";
	case OBSERVE: return "OBSERVE";
	case WASTE_NOT: return "WASTE_NOT";
	case VENERATION: return "VENERATION";
	case STANDARD_TOUCH: return "STANDARD_TOUCH";
	case GREAT_STRIDES: return "GREAT_STRIDES";
	case INNOVATION: return "INNOVATION";
	case FINAL_APPRAISAL: return "FINAL_APPRAISAL";
	case WASTE_NOT_II: return "WASTE_NOT_II";
	case BYREGOTS_BLESSING: return "BYREGOTS_BLESSING";
	case MUSCLE_MEMORY: return "MUSCLE_MEMORY";
	case CAREFUL_SYNTHESIS: return "CAREFUL_SYNTHESIS";
	case MANIPULATION: return "MANIPULATION";
	case PRUDENT_TOUCH: return "PRUDENT_TOUCH";
	case ADVANCED_TOUCH: return "ADVANCED_TOUCH";
	case REFLECT: return "REFLECT";
	case PREPARATORY_TOUCH: return "PREPARATORY_TOUCH";
	case GROUNDWORK: return "GROUNDWORK";
	case DELICATE_SYNTHESIS: return "DELICATE_SYNTHESIS";
	case PRUDENT_SYNTHESIS: return "PRUDENT_SYNTHESIS";
	case TRAINED_FINESSE: return "TRAINED_FINESSE";
	case REFINED_TOUCH: return "REFINED_TOUCH";
	case IMMACULATE_MEND: return "IMMACULATE_MEND";
	case TRAINED_PERFECTION: return "TRAINED_PERFECTION";
	default:
		return "[UNKNOWN]";
	};
}
